#!/usr/bin/env bash

a=8
r='i=getchar(),t[p]=i*(i>0);'
p='putchar(t[p]);'

while (($# > 1)); do
    if [[ "$1" == -w ]]; then
        a=32
    elif [[ "$1" == -n ]]; then
        r='if(scanf("%d",(int*)&t[p])<0)t[p]=0;'
        p='printf("%d ",t[p]);'
    fi
    shift
done

cat > "$1.c" << EOF
#include <stdint.h>
#include <stdio.h>

int main(){
uint${a}_t t[65536] = {0};
uint16_t p = 0;
uint8_t i;
EOF

while read -n1 char; do
	case "$char" in
		\>) echo '++p;';;
		\<) echo '--p;';;
		\+) echo '++t[p];';;
		\-) echo '--t[p];';;
		\,) echo $r;;
		\.) echo $p;;
		\[) echo 'while(t[p]){';;
		\]) echo '}';;
	esac
done < "$1" >> "$1.c"

echo 'return 0;}' >> "$1.c"

cc -O3 -o "$1.out" "$1.c" && "./$1.out"
